services:
  birdflight:
    image: birdflight
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:80
    volumes:
      - /data/birdflight/user:/app/app/static/user
    restart: unless-stopped
